site_name: João Graça Gomes Personal Website
repo_url: https://joaogracagomes.github.io

edit_uri: tree/main/

theme:
  name: material
  custom_dir: docs
  logo: assets/iclogo.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  # SPA behaviour
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.annotate
extra:
  homepage: https://imperialcollegelondon.github.io/ReCoDE-home/

# Add here all the plugins you want to use.
# Don't forget to add them in requirements.txt as well.
plugins:
  - tags
  - search
  - include-markdown # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - mkdocs-jupyter
  - exclude:
      glob:
      - "LICENSE.md"

# Set settings for markdown extensions
markdown_extensions:
  - meta
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

# Render math in mkdocs
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML



